
dubbo:
  application:
    name: web_back
  registry:
    address:  zookeeper://152.136.157.169:2181
  consumer:
    check: false
    timeout: 4000
#    容错机制
    retries: 1
spring:
  thymeleaf:
    cache: false
fdfs:
  tracker-list:
    - 152.136.157.169:22122
#    连接超时时间
  connect-timeout: 5000
#  读取超时时间

  so-timeout: 5000
#  缩略图
  thumbImage:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
server:
  port: 8080
img:
  server: http://152.136.157.169
