spring:
  data:
    solr:
      host: http://47.112.136.15:8080/solr
  rabbitmq:
    host: 47.112.136.15
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
dubbo:
  application:
    name: find_service
  registry:
    address: zookeeper://47.112.136.15:2181
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 60000