spring:
  datasource:
    url: jdbc:mysql:///shop_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 47.112.136.15
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672

dubbo:
  registry:
    address:  zookeeper://47.112.136.15:2181
  protocol:
    name: dubbo
    port: -1
  application:
    name: service_goods
  consumer:
    check: false