server:
  port: 8083
dubbo:
  application:
    name: web_item
  registry:
    address: zookeeper://47.112.136.15:2181
  consumer:
    check: false
spring:
  rabbitmq:
    host: 47.112.136.15
    username: admin
    password: admin
    virtual-host: /admin